package com.mgt.service;
import com.mgt.dao.CommissionDAO;import com.mgt.model.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.stereotype.Service;import javax.transaction.Transactional;import java.time.LocalDate;import java.util.*;
@Service public class CommissionService {
 @Autowired private CommissionDAO dao; @Autowired private SellerWalletService wallet;
 @Transactional public Commission create(Order order,Seller seller,double gross){Commission old=dao.getByOrderAndSeller(order.getId(),seller.getId());if(old!=null)return old;double rate=seller.getCommissionRate()!=null?seller.getCommissionRate():10.0;rate=Math.max(0,Math.min(rate,100));Commission c=new Commission();c.setOrder(order);c.setSeller(seller);c.setGrossAmount(round(gross));c.setCommissionRate(rate);c.setCommissionAmount(round(gross*rate/100));c.setSellerAmount(round(gross-c.getCommissionAmount()));c.setStatus("PENDING");c.setCreatedAt(LocalDate.now());c.setCreditedToWallet(false);dao.save(c);return c;}
 public List<Commission> getAll(){return dao.getAll();} public List<Commission> getBySellerId(long id){return dao.getBySellerId(id);} public List<Commission> getByStatus(String s){return dao.getByStatus(s.toUpperCase());}
 @Transactional public boolean markPayable(long id){Commission c=dao.getById(id);if(c==null)return false;if("REVERSED".equals(c.getStatus())||"PAID".equals(c.getStatus()))throw new RuntimeException("Commission cannot be released");c.setStatus("PAYABLE");c.setPayableAt(LocalDate.now());wallet.creditAvailable(c);c.setCreditedToWallet(true);dao.update(c);return true;}
 public boolean markPaid(long id){Commission c=dao.getById(id);if(c==null)return false;c.setStatus("PAID");c.setPaidAt(LocalDate.now());dao.update(c);return true;}
 @Transactional public void markOrderOnHold(Order o){for(Commission c:dao.getByOrderId(o.getId()))if("PENDING".equals(c.getStatus())){c.setStatus("ON_HOLD");dao.update(c);}}
 @Transactional public void markOrderPayable(Order o){for(Commission c:dao.getByOrderId(o.getId()))if(!"PAYABLE".equals(c.getStatus())&&!"PAID".equals(c.getStatus())&&!"REVERSED".equals(c.getStatus()))markPayable(c.getId());}
 @Transactional public void markOrderRefunded(Order o){for(Commission c:dao.getByOrderId(o.getId())){if(Boolean.TRUE.equals(c.getCreditedToWallet()))wallet.reverseCommission(c,"Refund/return reversal for order "+o.getOrderCode());c.setStatus("REVERSED");c.setReversedAt(LocalDate.now());c.setReversalReason("ORDER_REFUNDED");dao.update(c);}}
 public Map<String,Object> sellerSummary(long id){return summarize(dao.getBySellerId(id));}public Map<String,Object> globalSummary(){return summarize(dao.getAll());}
 private Map<String,Object> summarize(List<Commission> a){double gross=0,platform=0,seller=0,paid=0,payable=0,pending=0,onHold=0,reversed=0;for(Commission c:a){gross+=v(c.getGrossAmount());platform+=v(c.getCommissionAmount());seller+=v(c.getSellerAmount());String s=c.getStatus();if("PAID".equals(s))paid+=v(c.getSellerAmount());else if("PAYABLE".equals(s))payable+=v(c.getSellerAmount());else if("ON_HOLD".equals(s))onHold+=v(c.getSellerAmount());else if("REVERSED".equals(s))reversed+=v(c.getSellerAmount());else pending+=v(c.getSellerAmount());}Map<String,Object> m=new LinkedHashMap<>();m.put("count",a.size());m.put("grossAmount",round(gross));m.put("platformCommission",round(platform));m.put("sellerAmount",round(seller));m.put("paidAmount",round(paid));m.put("payableAmount",round(payable));m.put("onHoldAmount",round(onHold));m.put("pendingAmount",round(pending));m.put("reversedAmount",round(reversed));return m;}private double v(Double x){return x==null?0:x;}private double round(double x){return Math.round(x*100.0)/100.0;}
}
